package net.guides.springboot.registration_login_demo.entity;

import jakarta.persistence.*;
import jakarta.persistence.Id;

import java.util.List;

//  mapped to a database table
@Entity
// mapped to a database table called roles
@Table(name = "roles")
public class Role {

    // specifies that the field id is the primary key for the database table
    @Id
    // specifies that the primary key values are automatically
    // generated by the database using an identity column
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String name;

    @ManyToMany(mappedBy = "roles")
    private List<User> users;

    public Role() {
    }

    public Role(Long id, String name, List<User> users) {
        this.id = id;
        this.name = name;
        this.users = users;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public List<User> getUsers() {
        return users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }
}
