package net.guides.springboot.registration_login_demo.entity;

import jakarta.persistence.*;

import java.io.Serial;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

//  mapped to a database table
@Entity
// mapped to a database table called users
@Table(name="users")
public class User implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    //  specifies that the field id is the primary key for the database table.
    @Id
    // specifies that the primary key values are automatically generated by the
    // database using an identity column
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // specify that the field name cannot be null in the database table.
    @Column(nullable = false)
    private String name;

    // specify that the fields email cannot be null and
    // must be unique in the database table.
    @Column(nullable = false, unique = true)
    private String email;

    // specify that the fields password cannot be null in the database table.
    @Column(nullable = false)
    private String password;

    // specifies that the relationship between User and Role entities
    // is many-to-many.
    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    // It specifies the name of the join table (users_roles) and the names of
    // the foreign key columns in the join table (USER_ID and ROLE_ID).
    @JoinTable(
            name="users_roles",
            joinColumns = {@JoinColumn(name="USER_ID", referencedColumnName = "ID")},
            inverseJoinColumns = {@JoinColumn(name="ROLE_ID", referencedColumnName = "ID")})
    private List<Role> roles = new ArrayList<>();


    public User() {
    }

    public User(Long id, String name, String email, String password, List<Role> roles) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.password = password;
        this.roles = roles;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }

}
